### PR TITLE
Update for the latest rust nightly

### PR DESCRIPTION
**Pull request by darayus**

### CODE REVIEW

**Comment by michaelsproul** [comment]
Thanks so much! Great work!

**Comment by darayus** [comment]
You might want to bump the version number on crates.io as the version that is up there doesn't work with the latest nightly :smiley:.

**Comment by michaelsproul** [comment]
Done!

Unfortunately the rest of the Cargo ecosystem is looking a bit sad at the moment!

**Comment by darayus** [comment]
Thanks :+1:!

**Pull request merged**
